### ISSUE TITLE
hi, can you help?

### ISSUE THREAD

**Issue by ghost** [CorwinDev/BotsCord#12]
i am getting this error,

(node:22248) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
    at Mongoose.connect (C:\Users\louis\Documents\GitHub\test\node_modules\mongoose\lib\index.js:410:5)
    at Object.<anonymous> (C:\Users\louis\Documents\GitHub\test\index.js:7:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MONGOOSE'
}
Warning
TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (C:\Users\louis\Documents\GitHub\test\index.js:70:64)
    at process.emit (node:events:525:35)
    at doEmitWarning (node:internal/process/warning:89:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Uncaught Exception
C:\Users\louis\Documents\GitHub\test\index.js:53
    client.channels.cache.get(client.config.bot.channels.error).send(`Uncaught Exception: ${err}`);
                                                                                               ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (C:\Users\louis\Documents\GitHub\test\index.js:53:64)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25)

Node.js v18.14.1

**Comment by CorwinDev** [comment]
Did you fill in the config?

**Comment by ghost** [comment]
yes

**Comment by ghost** [comment]
that of MONGOOSE that error i have with every boy that i use

**Comment by ghost** [comment]
hi, i am still getting 

```
TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (C:\Users\louis\Documents\GitHub\BotsCord\index.js:70:64)
    at process.emit (node:events:525:35)
    at doEmitWarning (node:internal/process/warning:89:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Uncaught Exception
C:\Users\louis\Documents\GitHub\BotsCord\index.js:53
    client.channels.cache.get(client.config.bot.channels.error).send(`Uncaught Exception: ${err}`);
                                                               ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (C:\Users\louis\Documents\GitHub\BotsCord\index.js:53:64)
    at process.emit (node:events:513:28)
    at process._fatalException (node:internal/process/execution:149:25)

Node.js v18.12.1
```
